// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/all-cat-icons/Compass.tsx": () => import("../components/mockups/all-cat-icons/Compass.tsx"),
  "./components/mockups/all-cat-icons/Current.tsx": () => import("../components/mockups/all-cat-icons/Current.tsx"),
  "./components/mockups/all-cat-icons/Sparkle.tsx": () => import("../components/mockups/all-cat-icons/Sparkle.tsx"),
  "./components/mockups/all-cat-icons/Squares.tsx": () => import("../components/mockups/all-cat-icons/Squares.tsx"),
  "./components/mockups/all-cat-icons/Tag.tsx": () => import("../components/mockups/all-cat-icons/Tag.tsx")
};
